email_send_get:
    path: /email/send
    controller: App\Controller\EmailController::showForm
    methods: [GET]

email_send_post:
    path: /email/send
    controller: App\Controller\EmailController::sendEmail
    methods: [POST]
